spring:
  application:
    name: config-client
eureka:
  instance:
    hostname: 172.18.10.34
  client:
    service-url:
      defaultZone: http://eurekamaster.chunzeacademy.com:8761/eureka/,http://eurekaslave.chunzeacademy.com:8761/eureka/